context("test-error")

test_that("should fail", {
  expect_equal(1 + 1, 3)
})
